### PR TITLE
Outreach minutes catchup

### PR DESCRIPTION
**Pull request by altsalt**
Tried to cleanup and sort out the last few meetings into actionable TODOs.

### CODE REVIEW

**Comment by tinkerwilco** [comment]
looks good, thanks for compiling these notes for saving. 👍

**Review by tinkerwilco — APPROVED** [review]
Looks like 6/29 is the latest fine and contains up-to-date meeting notes. TODO items make sense. btw I'm still working on a script that can go through the meeting notes and pull out all the TODOs, but for now we just have to kinda review each committee's notes weekly or something in order to track all the TODOs, correct?

**Comment by altsalt** [comment]
Yeap, the meeting notes carry TODOs and my intention was to have them revisited each meeting, if they lingered beyond a week, they'd be manually turned into GH issues. That said, if your script handles that bit automagically, I can see value in just having them immediately become issues. We can then link the issue from the agenda and be checking them out directly from the pad in a screen share or something.

**Review by tinkerwilco — COMMENTED** [review]
LGTM

**Pull request merged**
