### PR TITLE
Add volunteer resources for 2020

### PR DESCRIPTION
**Pull request by lucywyman**
This adds a Talk Moderator checklist, frequently asked questions, and
list of IRC channels to the organization repo as resources for 2020
volunteers. More resources coming soon!

### CODE REVIEW

**Comment by altsalt** [comment]
These are awesome, thanks @lucywyman !!!

**Review by sntxrr — APPROVED** [review]
Looks good to me

**Review by funnelfiasco — APPROVED** [review]
LGTM. We should add some quick IRC command references, but than can go in separately.

**Comment by lucywyman** [comment]
Ok merging for now and we can update

**Comment by altsalt** [comment]
Unsure how you were not in the GH staff team yet, but an invite has been sent. Thanks so much for everything @lucywyman !

**Pull request merged**
